# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datatables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatablestate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
